services:
  backend:
    build:
      context: ./back
    environment:
      - NODE_ENV=production
      - PORT=5000
    restart: unless-stopped
    networks:
      - app

  frontend:
    build:
      context: ./front
    environment:
      - NODE_ENV=production
      - PORT=3000
      # - NEXT_PUBLIC_API_URL=
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - app

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
      - frontend
    restart: unless-stopped
    networks:
      - app
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1/healthz"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 40s

networks:
  app: {}