name: Deploy to SpaceWeb

on:
    push:
        branches: ["main"]
    workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Deploy over SSH
              uses: appleboy/ssh-action@v1.0.3
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USERNAME }}
                  key: ${{ secrets.SSH_KEY }}
                  command_timeout: 20m
                  script: |
                      set -euo pipefail
                      export DEBIAN_FRONTEND=noninteractive

                      if ! command -v curl >/dev/null 2>&1; then
                        sudo apt-get update -y
                        sudo apt-get install -y curl ca-certificates
                      fi

                      if ! command -v docker >/dev/null 2>&1; then
                        curl -fsSL https://get.docker.com | sh
                      fi

                      if ! docker compose version >/dev/null 2>&1; then
                        sudo apt-get update -y
                        sudo apt-get install -y docker-compose-plugin
                      fi

                      if ! command -v git >/dev/null 2>&1; then
                        sudo apt-get update -y
                        sudo apt-get install -y git
                      fi

                      sudo mkdir -p /opt/portfolio
                      sudo chown -R "$USER":"$USER" /opt/portfolio

                      if [ ! -d /opt/portfolio/.git ]; then
                        git clone https://github.com/Farylve/TEST.git /opt/portfolio
                      else
                        cd /opt/portfolio
                        git fetch --all
                        git reset --hard origin/main
                      fi

                      cd /opt/portfolio
                      sudo docker compose -f docker-compose.prod.yml down
                      sudo docker compose -f docker-compose.prod.yml up -d --build --force-recreate

                      echo "Waiting for containers to start..."
                      sleep 15
                      
                      echo "Checking container status..."
                      docker compose -f docker-compose.prod.yml ps
                      
                      echo "Checking logs..."
                      docker compose -f docker-compose.prod.yml logs --tail=20
                      
                      echo "Waiting for app to become healthy..."
                      for i in {1..30}; do
                        if curl -fsS http://localhost/healthz >/dev/null 2>&1; then
                          echo "Health check passed!"
                          break
                        fi
                        echo "Attempt $i/30 failed, waiting..."
                        sleep 5
                      done
                      
                      echo "Final container status:"
                      docker compose -f docker-compose.prod.yml ps
                      
                      if ! curl -fsS http://localhost/healthz >/dev/null 2>&1; then
                        echo "Health check failed after 30 attempts"
                        echo "Container logs:"
                        docker compose -f docker-compose.prod.yml logs --tail=50
                        exit 1
                      fi
                      
                      echo "Deployment successful!"

            - name: Install Node for E2E tests
              uses: actions/setup-node@v4
              with:
                  node-version: "20"

            - name: Install Playwright and deps
              working-directory: ./front
              run: |
                  npm ci
                  npx playwright install --with-deps

            - name: Run E2E tests against production
              env:
                  BASE_URL: http://farylve.online
              working-directory: ./front
              run: npx playwright test
