name: Deploy to Server

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub (optional)
      if: github.event_name == 'push' && env.DOCKER_USERNAME != '' && env.DOCKER_PASSWORD != ''
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and test
      run: |
        docker compose -f docker-compose.yml build
        docker compose -f docker-compose.yml up -d
        sleep 30
        # Test backend health
        curl -f http://localhost:5000/api/health || exit 1
        # Test frontend
        curl -f http://localhost:3000 || exit 1
        docker compose -f docker-compose.yml down

    - name: Deploy to server
      if: github.event_name == 'push'
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        port: ${{ secrets.PORT || 22 }}
        script: |
          cd ${{ secrets.SERVER_PATH || '/opt/portfolio' }}
          git pull origin main
          docker compose -f docker-compose.prod.yml down
          docker compose -f docker-compose.prod.yml build --no-cache
          docker compose -f docker-compose.prod.yml up -d
          docker system prune -f

    - name: Health check after deployment
      if: github.event_name == 'push'
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        port: ${{ secrets.PORT || 22 }}
        script: |
          sleep 30
          curl -f http://localhost:5000/api/health || exit 1
          echo "Deployment successful!"